sudo: required
services:
- docker
language: node_js
node_js:
- '8'
before_script:
- npm test
script:
- sh .travis/dockerhub/build.sh
- sh .travis/heroku/build.sh
after_success:
- npm run infra
after_script:
- sh .travis/dockerhub/push.sh
- sh .travis/heroku/push.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=storage
  - HEROKU_APP_NAME=iosr2017storage
  - secure: QQCOB9oluCcKvuH7RIHCMc0k9uZxxZ9yP2+HXn3dIMyi4hhOrGrHu0U9S/GgmIkgSXljz7HGWyDvqit+l84Wa/IhijlF9ZtTdAAGo9gYaX6YYnWirjThUGATsIX3H97YOlH7+YsU9jNpwlaezKokGGZoOVsMxThrV6V/2b6Cq9Qjt2uYE9lyv2GGolbOGaXpeKSK76S1aogKwt9kdZlwXPyjgDSomrmKfpBJ6q9ksOpsUmAWopckHdyffLzcYEWH9xJrf3V8Gh4ZqiguIXnEnoMwwmmroyvfMvv3evc3vlLGZQ7ty3Bm2JMFms8GVQaLCc/O7nvTygc3bw2WR3BDMKVyXz6pBN7EdrPreviQyLgiC8T4yo3fLU330bLt+oxcq1eKaTZFn7PK0TPx5+PFASz/IsIihPOBpHuP9emGUClSzPUElKtg3D8V9QMWRoHZDY/+vfL9N/OHFzFzNPH+OWCaVcFTfb2Ffxjg1EZTj0yshvvhnsqW3N3jHiv6ZQViuXKQDchmvpMbskdbyQTSzNHDtJArALbUywfJFS02hrnhMyGUGRFwfgwmvGkTEm7hVjrCa46uE19UH9q0p6VLAMLQYq/ENj8HvR6yU8vOtaRm9yF0p3FaBMTVfWj4yUu4AJ+dgCLDS+bNePwybD/YrGdihDNvDbVwncvhy/NtlX4=
  - secure: Tzn/YFDfTAFmZ0J2tyG7gLF3M7GPwz89z6j1MSrhrPePW7yIE9ktcmVHoewCzHddoeXgQsz2+ZonAariYRmFJ132CKTw2XxyNjxUpLWmxaFxbXodXbl6NgwfNrKCa71jPbvBEFAL2Tlom9zWVDtEnFihNgBnpxfZyHoanEpiZAEPE1T8KWdtyp2Njl8B/4tSAAxtC8oUyi+/sWa9wJ1z/0mGc7neQTcGNJ3dW6UB1LW0jEZymrVfgQ1zB7eYbHTcjzmhxW7jIsGB1WF7ambPZLBrsvoQdGm6MvhzG0jDDl5xdSIwFkjVoPTW2EvnQPMRvo1PsXw7AP00olYh479C2b8c7/wMYAS6HKYi412XxEi+G1JRaTRvXBc0a224h06Qa5TeHK30iyWF2fJekIfJIjNPPrlEQjsDGEzAc8QRtEHf+esTppoKjQWkoG9kKb96a/+1CfxwsjllxSZ4AsLJQJactqdrg8/jvP4FqRjYnzgKBPG70U8bMeIo3kHXX/zbYcVf3FKwHAd7a6kyCyOzUl2xaKHKgMfkTTzjm3hZHVfdggJkkrWc6ijHjoumBjuwkyhaNvYgAfhu3eTCVPr1G17PeTxIokLal8TAM5P2lLacN2BMdNDCtBa05rXqlLSjOXTvI7mO37o3NDl3dPdzFnq2l8BP0fRBm93BnS2MVUc=
