sudo: required
git:
  depth: false
services:
- docker
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_c597cf9f254c_key -iv $encrypted_c597cf9f254c_iv -in .netrc.enc -out .netrc -d
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=storage
  - HEROKU_APP_NAME=iosr2017storage
  - secure: rhIGh6VXd+1t6whhb5uZpBT9erk8ErjXghsdlpWzZVnjx3Pj3DCxf9T3ASUOXlNOsvW5diTh+MgNGbxfjY596CcBVTQ0ntWQf97948M1wY3Egv8R/EhuhoP9R+RVnIR0ngrowRrd3yvPENBJQ3zm7D+hLWa3/JcVSq1i/ULYS74tMeOVyp4ecImHFsQZ6W1kRkbDK81mDgd7pBO8gJORZn2/PrF7I2oGzLR6AJz9YoTQ9lxbSaq+uO7hNMXi47c309fFOV4uhxeRlNFjtrRO57qrQiBypTtaa+NKowNJ7fIIjsApSY0IVTNjgHIo5s9xeV/R1pJ30pF/2KnrP8JVCNTycVGNv5AQcasXTTQT7VLjDCFfEfQjtb0/wIDJoZuVjtBO5Ge/7Pj0a/Ox+2oobdbEZyccjl43YemHv4cSr8Kmj+8XQeQjCYq414wLiQBgkIXmVZrpkQkQt70gE+4ygWtXXRI9wvTYNLN2yPKUxPbeob5sbEefPYxlYM+W+f18Wj18at0axTdoNR8195KTZC7utinpnWhSMU1IARR4xscRzTzhnvwlYmlU1qj7xhbxJMr1YC46EQwYsu3WElUO1rNK3G6mNf7hl1VgIeO4nmBDQeTCy5xafQM959bHhcx9MqUnRGtSj1aY3VYtPRgwVSFsAjkKSKv8jTqCIUcM6TY=
  - secure: rGm1guR8CVKPCsZ9g0+M75bQVkiCTKgvZtbnvQ4OgRuE6V2UaryIxGW1SuD5tgViWjXDBeBRlmWtD+1m31w1+hFiioh2qbLw/K4KKvP4byAYkCm2gMXW2FOmpk07NeJiKI+bzSanWHZQnm3Os/X2jasDFfPY7CC0jZ4ZHw9m/jJAUWhc8j5mPpzzQP+MPkSDtt2aT+SiLHtcTqZAFU3BNqRiS9wfKIx9EPLAJF6zXM4Td4Xwuq1pNfWdpRZBS436Q5cX6QClYwFMHcaObb3tFq2LUBxjV/5zT1VmBvT7e8DiclOxXePAbGt/Um4r8GyS8EexKDc9PWDSXDQ0RGlM3msRZoiF8/yODkv0TkWuWiOFINVDfQcNwM1rTtpdB6d0JmWPuJvr93DxRmb+5gi/Dr7islRtrLG0YR0+ZsyThvxVkvcnrsHe+770Q31MqqFSihv++tmFsq03ueFLaQjnjhMbWPESgGae4hrdV25HVLDX5VxPMydZRIcO6bWFYU0l1Go1SQVEGvyj8lVXmtEU9hPFXc906C13q7fO8dXAkhn4YJwQbAEY4OwcqcD+P3611KDWq9fYSxLQ7MWQ6AVlmPhSoauiTHW8SMEB+YR7TFweaA9IBSWwKYw61LEBuZAFFGO9G+XNS0AMLHCEror4tOW9zixdSIoc/XJkkIft0RA=
